/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaappmongodb;

import java.util.ArrayList;
import java.util.List;
import javaappmongodb.controle.SituacaoMatriculaPeriodoControle;
import javaappmongodb.model.dao.SituacaoMatriculaPeriodo;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Edvania
 */
public class JFSituacaoMatriculaPeriodo extends javax.swing.JFrame {

    private SituacaoMatriculaPeriodoControle controle;
    private List<SituacaoMatriculaPeriodo> situacaoMatriculaPeriodos = new ArrayList<SituacaoMatriculaPeriodo>();
    private AbstractTableModel tableModel = new SituacaoMatriculaPeriodoTableModel();
    
    /**
     * Creates new form JFSituacaoMatriculaPeriodo
     */
    public JFSituacaoMatriculaPeriodo() {
        initComponents();
    }

    JFSituacaoMatriculaPeriodo(String ip, String banco, String porta) {
        controle = new SituacaoMatriculaPeriodoControle(ip, banco, porta);
        initComponents();
    }

    public List<SituacaoMatriculaPeriodo> getSituacaoMatriculaPeriodos() {
        return controle.getSituacaoMatriculaPeriodos();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(tableModel);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFSituacaoMatriculaPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFSituacaoMatriculaPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFSituacaoMatriculaPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFSituacaoMatriculaPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFSituacaoMatriculaPeriodo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    class SituacaoMatriculaPeriodoTableModel extends AbstractTableModel {
        
        private String[] columnName = new String[] {
                "ID", "SITUAÇÃO"
                };

        public SituacaoMatriculaPeriodoTableModel() {
        }

        @Override
        public int getRowCount() {
            return getSituacaoMatriculaPeriodos().size();
        }

        @Override
        public int getColumnCount() {
            return columnName.length;
        }

        @Override
        public String getColumnName(int column) {
            return columnName[column];
        }
        
        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            SituacaoMatriculaPeriodo s = getSituacaoMatriculaPeriodos().get(rowIndex);
            switch(columnIndex) {
                case 0: return s.getId();
                case 1: return s.getDescricao();
            }
            return null;
        }
    }
    
}
